version: "3"
services:
  quakeworld:
    image: zobees/quakeworld:latest
    container_name: quakeworld_server
    ports:
      - "27500:27500/udp"  # Standard QuakeWorld port
    volumes:
      - ./id1:/id1         # Montera din id1-mapp
    restart: unless-stopped
